name: Bru CLI with multiple Collections

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  bru-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        collection: 
          - github-rest-api-collection
          - cat-facts-api-collection
          - bruno-echo-api-collection
    name: Run ${{ matrix.collection }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli
      
      - name: Run API Tests
        working-directory: ./bruno-collections/${{ matrix.collection }}
        run: |
          pwd
          ls -la
          bru run --env Github --reporter-html results.html
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.collection }}-results
          path: bruno-collections/${{ matrix.collection }}/results.html
